# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InterceptionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irf_number', models.CharField(max_length=20, unique=True)),
                ('date_time_of_interception', models.DateTimeField()),
                ('drugged_or_drowsy', models.BooleanField(default=False)),
                ('meeting_someone_across_border', models.BooleanField(default=False)),
                ('seen_in_last_month_in_nepal', models.BooleanField(default=False)),
                ('traveling_with_someone_not_with_her', models.BooleanField(default=False)),
                ('wife_under_18', models.BooleanField(default=False)),
                ('married_in_past_2_weeks', models.BooleanField(default=False)),
                ('married_in_past_2_8_weeks', models.BooleanField(default=False)),
                ('less_than_2_weeks_before_eloping', models.BooleanField(default=False)),
                ('between_2_12_weeks_before_eloping', models.BooleanField(default=False)),
                ('caste_not_same_as_relative', models.BooleanField(default=False)),
                ('caught_in_lie', models.BooleanField(default=False)),
                ('doesnt_know_going_to_india', models.BooleanField(default=False)),
                ('running_away_over_18', models.BooleanField(default=False)),
                ('running_away_under_18', models.BooleanField(default=False)),
                ('going_to_gulf_for_work', models.BooleanField(default=False)),
                ('no_address_in_india', models.BooleanField(default=False)),
                ('no_company_phone', models.BooleanField(default=False)),
                ('no_appointment_letter', models.BooleanField(default=False)),
                ('valid_gulf_country_visa', models.BooleanField(default=False)),
                ('passport_with_broker', models.BooleanField(default=False)),
                ('job_too_good_to_be_true', models.BooleanField(default=False)),
                ('not_real_job', models.BooleanField(default=False)),
                ('couldnt_confirm_job', models.BooleanField(default=False)),
                ('no_bags_long_trip', models.BooleanField(default=False)),
                ('shopping_overnight_stuff_in_bags', models.BooleanField(default=False)),
                ('no_enrollment_docs', models.BooleanField(default=False)),
                ('doesnt_know_school_name', models.BooleanField(default=False)),
                ('no_school_phone', models.BooleanField(default=False)),
                ('not_enrolled_in_school', models.BooleanField(default=False)),
                ('reluctant_treatment_info', models.BooleanField(default=False)),
                ('no_medical_documents', models.BooleanField(default=False)),
                ('fake_medical_documents', models.BooleanField(default=False)),
                ('no_medical_appointment', models.BooleanField(default=False)),
                ('doesnt_know_villiage_details', models.BooleanField(default=False)),
                ('reluctant_villiage_info', models.BooleanField(default=False)),
                ('reluctant_family_info', models.BooleanField(default=False)),
                ('refuses_family_info', models.BooleanField(default=False)),
                ('under_18_cant_contact_family', models.BooleanField(default=False)),
                ('under_18_family_doesnt_know', models.BooleanField(default=False)),
                ('under_18_family_unwilling', models.BooleanField(default=False)),
                ('over_18_family_doesnt_know', models.BooleanField(default=False)),
                ('over_18_family_unwilling', models.BooleanField(default=False)),
                ('noticed_hesitant', models.BooleanField(default=False)),
                ('noticed_nervous_or_afraid', models.BooleanField(default=False)),
                ('noticed_hurrying', models.BooleanField(default=False)),
                ('noticed_drugged_or_drowsy', models.BooleanField(default=False)),
                ('noticed_new_clothes', models.BooleanField(default=False)),
                ('noticed_dirty_clothes', models.BooleanField(default=False)),
                ('noticed_carrying_full_bags', models.BooleanField(default=False)),
                ('noticed_village_dress', models.BooleanField(default=False)),
                ('noticed_indian_looking', models.BooleanField(default=False)),
                ('noticed_typical_village_look', models.BooleanField(default=False)),
                ('noticed_looked_like_agent', models.BooleanField(default=False)),
                ('noticed_caste_difference', models.BooleanField(default=False)),
                ('noticed_young_looking', models.BooleanField(default=False)),
                ('noticed_waiting_sitting', models.BooleanField(default=False)),
                ('noticed_walking_to_border', models.BooleanField(default=False)),
                ('noticed_roaming_around', models.BooleanField(default=False)),
                ('noticed_exiting_vehicle', models.BooleanField(default=False)),
                ('noticed_heading_to_vehicle', models.BooleanField(default=False)),
                ('noticed_in_a_vehicle', models.BooleanField(default=False)),
                ('noticed_in_a_rickshaw', models.BooleanField(default=False)),
                ('noticed_in_a_cart', models.BooleanField(default=False)),
                ('noticed_carrying_a_baby', models.BooleanField(default=False)),
                ('trafficker_taken_into_custody', models.CharField(blank=True, max_length=20, null=True)),
                ('how_sure_was_trafficking', models.IntegerField(choices=[(1, b'1 - Not at all sure'), (2, b'2 - Unsure but suspects it'), (3, b'3 - Somewhat sure'), (4, b'4 - Very sure'), (5, b'5 - Absolutely sure')])),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_story_code', models.CharField(max_length=255, unique=True)),
                ('story_text', models.TextField()),
                ('full_name', models.CharField(max_length=255)),
                ('interception_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.InterceptionRecord')),
            ],
        ),
        migrations.CreateModel(
            name='StoryDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Donor')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story')),
            ],
        ),
    ]
