# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interceptionrecord',
            name='date_time_of_interception',
        ),
    ]
